package main

import "strings"

// irCommands maps plain-text IR command names to their decimal codes
// for the NAD C725BEE receiver (NEC format).
var irCommands = map[string]int{
	"am":                       130,
	"aux":                      155,
	"blend":                    53,
	"brightness":               56,
	"cd":                       133,
	"dab":                      126,
	"display_tuner":            38,
	"fm":                       129,
	"media_player":             192,
	"mp_int_backlight":         106,
	"mp_int_down":              98,
	"mp_int_enter":             101,
	"mp_int_left":              99,
	"mp_int_menu":              102,
	"mp_int_pause":             108,
	"mp_int_play":              107,
	"mp_int_play/pause":        103,
	"mp_int_random":            104,
	"mp_int_repeat":            105,
	"mp_int_right":             100,
	"mp_int_skip/scan_back":    113,
	"mp_int_skip/scan_forward": 112,
	"mp_int_stop":              109,
	"mp_int_up":                97,
	"mute":                     148,
	"phono/disc":               137,
	"power_off":                200,
	"power_on":                 37,
	"power_toggle":             128,
	"preset_down":              209,
	"preset_up":                210,
	"search_down":              134,
	"search_up":                135,
	"sleep":                    32,
	"source_down":              29,
	"source_up":                26,
	"speaker_a":                206,
	"speaker_b":                207,
	"tape_1":                   141,
	"tone_defeat":              220,
	"tune_down":                211,
	"tune_up":                  212,
	"tuner":                    221,
	"tuner_0":                  199,
	"tuner_1":                  138,
	"tuner_2":                  142,
	"tuner_3":                  146,
	"tuner_4":                  150,
	"tuner_5":                  139,
	"tuner_6":                  143,
	"tuner_7":                  147,
	"tuner_8":                  151,
	"tuner_9":                  152,
	"tuner_delete":             246,
	"tuner_enter":              197,
	"tuner_memory":             245,
	"tuner_mode":               55,
	"video_6":                  30,
	"volume_down":              140,
	"volume_up":                136,
	"zone_am":                  161,
	"zone_aux":                 167,
	"zone_cd":                  165,
	"zone_disc":                166,
	"zone_fm":                  162,
	"zone_local":               179,
	"zone_media_player":        169,
	"zone_mute":                160,
	"zone_power_off":           177,
	"zone_power_on":            176,
	"zone_power_toggle":        180,
	"zone_preset_down":         164,
	"zone_preset_up":           163,
	"zone_search_down":         184,
	"zone_search_up":           183,
	"zone_source_down":         187,
	"zone_source_up":           186,
	"zone_tape":                174,
	"zone_tune_down":           182,
	"zone_tune_up":             181,
	"zone_tuner":               175,
}

// LookupIR performs a case-insensitive lookup of an IR command name.
// Spaces are converted to underscores so both forms work.
// Returns the decimal code and true if found, or 0 and false if not.
func LookupIR(name string) (int, bool) {
	normalized := strings.ToLower(strings.TrimSpace(name))
	normalized = strings.ReplaceAll(normalized, " ", "_")
	code, ok := irCommands[normalized]
	return code, ok
}
